---
version: '3'
services:
  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: download-data
    volumes:
      - ".:/freqtrade/user_data/data"
    command: >
      download-data
      --timerange ${START_DATE:-20200101}-${END_DATE:-20220401}
      --timeframe 15m 30m 1h 4h 1d 1w
      --datadir user_data/data/${EXCHANGE:-binance}
      --config user_data/data/pairlists.json
      --config user_data/data/pairlists-${STAKE_CURRENCY:-usdt}.json
      --config user_data/data/${EXCHANGE:-binance}-${STAKE_CURRENCY:-usdt}-static.json
